### ISSUE TITLE
Recording actions causes stories to unmount and remount

### ISSUE THREAD

**Issue by wyattdanger** [kadirahq/react-storybook#136]
I have a story that displays 259 Icons. Whenever I record an `action`, it appears as if all of the components are unmounted from the DOM and remounted, resulting in 259 calls to each of `componentWillUnmount`, `componentWillMount`, and `componentDidMount`. Here is a screenshot from the console: (the timer measures from `componentWillMount` to `componentDidMount` of a component which contains the story).

![screen shot 2016-04-21 at 6 04 48 pm](https://cloud.githubusercontent.com/assets/72922/14728670/b88cf29c-07eb-11e6-905a-272429e97d9a.png)

This results in a clunky story, because each time I click on an Icon (hoping to record the icon's name in an action), the page freezes up for over a second. Would be great to avoid unmounting and remounting each time.

**Comment by arunoda** [comment]
We fixed this. Could you try to use the latest version?

**Comment by wyattdanger** [comment]
I still see the issue on 1.17.1, (I should have mentioned that in the original issue).

**Comment by arunoda** [comment]
Okay. Then is a problem. Could you send me a sample app with this issue.

We will work on it test it.

**Comment by wyattdanger** [comment]
I'll work on an example, thank you

**Comment by arunoda** [comment]
Great.

**Comment by wyattdanger** [comment]
Closing until I have a good example
