### ISSUE TITLE
Module parse failed - Babel loader issue?

### ISSUE THREAD

**Issue by elado** [kadirahq/react-storybook#16]
Getting an error when running with this `.storybook/config.js`:

```js
import { configure } from '@kadira/storybook'

function loadStories() {
  require('../src/SomeComponent')
}

configure(loadStories, module)
```

Error:

```
ERROR in ./.storybook/config.js
Module parse failed: ***/.storybook/config.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { configure } from '@kadira/storybook'
|
| function loadStories() {
```

Seems like babel is not transpiling or it clashes with some config in my package?

**Comment by arunoda** [comment]
Are you using babel6? Try to see you have a .babelrc in your project root and it has es2015 and react presets. 

If not, try to create a sample repo and send to me. I will work on it.

**Comment by elado** [comment]
Yes. This is my `.babelrc` in the root of my project:

```json
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    "transform-runtime",
    "typecheck",
    "transform-decorators-legacy",
    "transform-class-properties",
    "add-module-exports",
    "import-asserts"
  ]
}
```

I'll work on a repo.

**Comment by arunoda** [comment]
Great.
BTW: check whether you are using NPM@3

**Comment by elado** [comment]
npm 3.7.3 and node 5.9.1

**Comment by arunoda** [comment]
Okay. Just to make it sure. Send me a sample repo. 
I will try to see what's going on here.

**Comment by travi** [comment]
I'm seeing something similar when my webpack config works correctly for production:
```js
ERROR in ./lib/shared/views/stories/primaryNav.jsx
Module parse failed: .../lib/shared/views/stories/primaryNav.jsx Line 7: Unexpected token <
You may need an appropriate loader to handle this file type.
| storiesOf('Primary Nav', module)
|     .add('empty nav', () => (
|         <PrimaryNav primaryNav={[]}/>
|     ));
 @ ./.storybook/config.js 6:4-57
```

* babel 6
* node 5.1.1
* npm 3.8.5

This is a fairly simple reference app that I thought would be a good testbed for this tool, but I can't seem to figure out how to get past this issue. This project is [public](https://github.com/travi/travi.org-admin/tree/react-storybook).

**Comment by travi** [comment]
Digging through the examples in more detail, I realized that I needed to add a `webpack.config.js` under `.storybook`. I thought I had read somewhere that the existing one in the root of the project would be used automatically, but adding this file got me past this issue.

**Comment by arunoda** [comment]
@travi I assume this because of the .jsx extension. 
Try the latest version: `v1.3.0`

**Comment by travi** [comment]
Thank you for that tip. Pulling down that latest version did enabled me to remove the diplicated `webpack.config.js` from under `.storybook`

I'm still getting `Error: inst.render is not a function` once I load it into the browser, which I'm assuming is related to the fact that this component is pure/stateless. I'm still digging in to confirm what I can, but I can log a separate issue for that if you don't have a quick recommendation.

**Comment by arunoda** [comment]
@travi Great. That's better for another issue.

**Comment by arunoda** [comment]
@elado  I assume this fixed. If not, please re-open and give me more info.

**Comment by elado** [comment]
Looks like it's fixed in the most recent version. Thanks!

**Comment by arunoda** [comment]
Great.

**Comment by robinspark** [comment]
This is broken again. To fix it, remove all carets/^ from package.json, then run:
`$ npm update`
//NOTE: running '`$ npm install`' wont fix the issue as it doesn't resolve micro version changes.

OR
`$ yarn upgrade`

**Comment by unutoiul** [comment]
when I run

`start-storybook -p 9001 -c node_modules/shared-components/.storybook`

I get the error 

`Module parse failed: Unexpected token (12:4) You may need an appropriate loader to handle this file type.`

when I do

`start-storybook -p 9001 -c .storybook`

works fine

can somebody explain what's the difference? I'm pulling my hair out...

I need to have shared components installed by npm so my storybook components will be sitting under node_modules folder.

Thanks,
Lucas

**Comment by ndelangen** [comment]
@unutoiul This is because the babel loader in our webpack config excludes `node_modules`.

If you want to do this you either:
- precompile everything so node_modules contains browser-ready code
- override our webpack config and configure it so it does pass `node_modules` through the babel-loader

**Comment by unutoiul** [comment]
yes my solution was:

**webpack.config.js**


const path = require('path');

module.exports = {
    module: {
        rules: [
            {
                test: /.jsx?$/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react']
                }
            }, {
                test: /\.scss$/,
                loaders: ["style-loader", "css-loader", "sass-loader"],
                include: path.resolve(__dirname, '../')
            }
        ]
    }
}
